name: Build and deploy Azure Functions - fn-nubestock-backend

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment a desplegar'
        required: false
        type: choice
        options:
          - NUBESTOCK_DEV
          - NUBESTOCK_UAT
          - NUBESTOCK_PRD
        default: 'NUBESTOCK_DEV'

jobs:
  deploy:
    permissions:
      contents: read
    uses: Nubestock/nubestock-workflows/.github/workflows/functions-deploy-action.yml@master
    with:
      environment: >-
        ${{
          github.event.inputs.environment != '' && github.event.inputs.environment
          || github.ref_name == 'develop' && 'NUBESTOCK_DEV'
          || github.ref_name == 'uat' && 'NUBESTOCK_UAT'
          || github.ref_name == 'master' && 'NUBESTOCK_PRD'
          || 'NUBESTOCK_DEV'
        }}
      node_version: '22'
    secrets:
      # === Secrets CORE de Azure (ÚNICOS OBLIGATORIOS) ===

      AZ_CLIENT_ID:        ${{ secrets.AZ_CLIENT_ID }}
      AZ_CLIENT_SECRET:    ${{ secrets.AZ_CLIENT_SECRET }}   # (temporal, hasta OIDC)
      AZ_TENANT_ID:        ${{ secrets.AZ_TENANT_ID }}
      AZ_SUBSCRIPTION_ID:  ${{ secrets.AZ_SUBSCRIPTION_ID }}

      AZ_FUNCTION_APP_NAME: ${{ secrets.AZ_FUNCTION_APP_NAME }}
      AZ_RESOURCE_GROUP:    ${{ secrets.AZ_RESOURCE_GROUP }}
